configure_dotfiles: no
configure_dock: true
configure_terminal: false
configure_osx: false
dockitems_remove:
  - Mail
  - TV
  - Podcasts
  - Music
  - Reminders
  - Notes
  - FaceTime
  - Photos
  - Maps
  - Keynote
  - Games
  - Numbers
  - Pages

osx_script: ""

mas_installed_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1661733229, name: "LocalSend" }
  - { id: 1584519802, name: "Vimlike" }
  - { id: 425955336, name: "Skitch - Snap. Mark up. Share." }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 823766827, name: "OneDrive" }
  - { id: 784801555, name: "Microsoft OneNote" }
  - { id: 1274495053, name: "Microsoft To Do" }
  - { id: 1544743900, name: "Hush Nag Blocker" }
  - { id: 6469021132, name: "PDFgear: PDF Editor & Reader" }
  - { id: 6747400514, name: "Tidora" }

homebrew_taps:
  - rogeriopradoj/cask-peazip
  - cosmincatalin/tap
  - amir1376/tap
  - deskflow/tap
  - mongodb/brew

homebrew_installed_packages:
  # Core utilities
  - autoconf
  - bash-completion
  - chezmoi
  - direnv
  - eza
  - bat
  - gzip
  - openssl
  - just
  - jc
  - pv
  - pipx
  - readline
  - ripgrep
  - ssh-copy-id
  - unzip
  - wget
  - zoxide
  - fzf
  - thefuck
  - autojump
  - starship
  - tw93/tap/mole
  - atuin

  # Development tools
  - asdf
  - ast-grep
  - commitizen
  - d2
  - doxygen
  - fastfetch
  - gettext
  - git
  - lazygit
  - gh
  - fd
  - gifsicle
  - goenv
  - graphviz
  - luarocks
  - libpq
  - neovim
  - jq
  - yq
  - libevent
  - mas
  - openjpeg
  - pngpaste
  - cloudflared
  - helix
  - repomix
  - mermaid-cli
  - mongodb-database-tools
  - pre-commit
  - superfile

  # Security tools
  - bitwarden-cli
  - detect-secrets
  - gpg

  # Network utilities
  - httpie
  - iperf
  - k6
  - nmap
  - rclone
  - wrk

  # Kubernetes & Cloud tools
  - argocd
  - dapr/tap/dapr-cli
  - dive
  - fluxcd/tap/flux
  - helm
  - helmfile
  - k9s
  - kube-ps1
  - kubeseal
  - kubernetes-cli
  - kubectx
  - kubetail
  - kustomize
  - opentofu
  - skaffold
  - weaveworks/tap/gitops
  - operator-sdk
  - stern
  - kubie
  - kubecolor

  # Miscellaneous
  - snappy
  - zsh-history-substring-search
  - pastel
  - pandoc
  # - deskflow
  - magic-wormhole
  - brew-explorer
  - croc

homebrew_cask_apps:
  # Browsers
  - firefox
  - microsoft-edge
  - thebrowsercompany-dia

  # Development & Programming
  - altair-graphql-client
  - apache-directory-studio
  - bruno
  - cursor
  - chromedriver
  - dbeaver-community
  - github
  - multipass
  - postman
  - warp
  - mongodb-compass
  - figma
  - lulu
  - pritunl
  - orbstack
  - ghostty
  - datagrip

  # Kubernetes & Cloud Tools
  - lens
  - freelens

  # Utility Software
  - another-redis-desktop-manager
  - evkey
  - free-download-manager
  - handbrake
  - licecap
  - marta
  - peazip
  - raycast
  - switchhosts
  - transmit
  - xpipe-io/tap/xpipe
  - jordanbaird-ice
  - freefilesync
  - cloudflare-warp
  - airparrot
  - reflector
  - adguard-vpn
  - teamviewer
  - pearcleaner
  - reminders-menubar
  - ab-download-manager
  - iterm2
  - freefilesync
  - flameshot
  - karabiner-elements

  # Fonts
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-nats

  # Communication & Collaboration
  - beeper
  - clickup
  - discord
  - microsoft-auto-update
  - microsoft-teams
  - notion
  - simplenote
  - telegram
  - readdle-spark
  - notion-mail

  # Media & Graphics
  - gimp
  - obs

  # Office & Productivity
  - onlyoffice
  - wpsoffice

pip_packages: []
  # - name: mkdocs
  # - name: pandoc
  # - name: pre-commit
